# Inserts a blank line between shell prompts
add_newline = true

format = """
$kubernetes$helm$docker_context$container
$git_branch$git_commit$git_state$git_metrics$git_status$terraform$package
$status$sudo$directory$character
"""
# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

[git_branch]
format = "[$symbol$branch]($style) "
symbol = "ğŸŒ± "
truncation_length = 10
truncation_symbol = ""

[kubernetes]
format = '[â›µ $context ](cyan)'
disabled = false

# Replace the "" symbol in the prompt with "âœ"
[character] # The name of the module we are configuring is "character"
success_symbol = "[â¯](bold green)" # The "success_symbol" segment is being set to "âœ" with the color "bold green"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
